kafka.topic:
  task-created-topic: task-created-topic

spring:
  redis:
    host: localhost
    posrt: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer